### PR TITLE
Check salt after reading headers

### PR DESCRIPTION
**Pull request by karmanyaahm**
Because AES128GCM mode reads the salt automatically. Supplying empty OperationalParams doesn't work because of that check

### CODE REVIEW

**Comment by karmanyaahm** [comment]
Btw thanks for this library. It has been really helpful to my project

**Comment by xakep666** [comment]
@karmanyaahm Thank you for this! Could you please add new test case for this?

**Comment by karmanyaahm** [comment]
I added a test for my use case, but it seems like it's causing the error test on Line 404 to fail with

```
    engine_test.go:404: Error block 0 decrypt failed: cipher: message authentication failed is not an invaild salt size
```
I don't fully understand what that test is supposed to do (with the message auth error vs the invalid salt error), is my change incompatible?

**Comment by xakep666** [comment]
@karmanyaahm I fixed this, please rebase on latest `master`

**Comment by karmanyaahm** [comment]
I did it

**Pull request merged**
